data_sources:
  psx_base_url: "https://dps.psx.com.pk"
  downloads_endpoint: "/download/closing_rates"
  pdf_filename_pattern: "{date}.pdf"

technical_indicators:
  sma_periods: [50, 200]
  rsi_period: 14
  macd:
    fast: 12
    slow: 26
    signal: 9

machine_learning:
  model_type: "RandomForest"
  min_training_samples: 200
  test_size: 0.2
  random_state: 42
  n_estimators: 100

storage:
  data_directory: "data"
  backup_directory: "backups"
  max_file_age_days: 365

logging:
  level: "INFO"
  file: "logs/psx_advisor.log"
  max_size_mb: 10
  backup_count: 5

performance:
  max_concurrent_requests: 5
  request_timeout: 30
  retry_attempts: 3
  retry_delay: 2